// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0GBqQw0B10B-fi3vshmw_GE-dQiOHKf8',
    appId: '1:1025358491308:web:7ef42673de09c8199eb909',
    messagingSenderId: '1025358491308',
    projectId: 'edsmovie-25e8b',
    authDomain: 'edsmovie-25e8b.firebaseapp.com',
    storageBucket: 'edsmovie-25e8b.appspot.com',
    measurementId: 'G-FSV834X0TZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDERXg_bBKkkBMCp89zSO2Wy5yR4W9o310',
    appId: '1:1025358491308:android:fbd2a481bf30dc1a9eb909',
    messagingSenderId: '1025358491308',
    projectId: 'edsmovie-25e8b',
    storageBucket: 'edsmovie-25e8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4hG1eNmLEuD-prRYj33ZVwS-Zap8qczI',
    appId: '1:1025358491308:ios:61744aa689430ed19eb909',
    messagingSenderId: '1025358491308',
    projectId: 'edsmovie-25e8b',
    storageBucket: 'edsmovie-25e8b.appspot.com',
    iosClientId: '1025358491308-813bq1tkug695n0e8nhan9po28qd8qgi.apps.googleusercontent.com',
    iosBundleId: 'com.example.rabbit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4hG1eNmLEuD-prRYj33ZVwS-Zap8qczI',
    appId: '1:1025358491308:ios:efce9de0f237e7329eb909',
    messagingSenderId: '1025358491308',
    projectId: 'edsmovie-25e8b',
    storageBucket: 'edsmovie-25e8b.appspot.com',
    iosClientId: '1025358491308-g9s7qmdeo154p07p7usroqbo7o7thcls.apps.googleusercontent.com',
    iosBundleId: 'com.example.rabbit.RunnerTests',
  );
}
